version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: prisma-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prisma
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prisma:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-migrations
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: ["sh", "-c", "npx prisma migrate deploy"]
    volumes:
      - .:/app

volumes:
  postgres_data:


